/* Generado por scripts/traducir.mjs desde traducciones/pt.json: no editar a mano.
   Lo que pinta el JS en la versión en portugués (pt/); main.js lo lee con t(). */
window.ElSotanoPT = {
 "Abrir menú": "Abrir menu",
 "Cerrar menú": "Fechar menu",
 "Consultar fechas": "Consultar datas",
 "657 77 11 35": "+34 657 77 11 35",
 "La puerta de la vidriera": "A porta do vitral",
 "Balcón": "Varanda",
 "Lavadora": "Máquina de lavar roupa",
 "Wifi": "Wi-Fi",
 "TV con streaming": "TV com streaming",
 "Ropa de cama y toallas": "Roupa de cama e toalhas",
 "Plancha": "Ferro de engomar",
 "Insonorización": "Insonorização",
 "Juegos de mesa": "Jogos de tabuleiro",
 "Adaptado a silla de ruedas": "Adaptado a cadeira de rodas",
 "El restaurante El Sótano, en una foto antigua": "O restaurante El Sótano, numa foto antiga",
 "Plaza de España y Ayuntamiento": "Plaza de España e Câmara",
 "{m} m · {min} min a pie": "{m} m · {min} min a pé",
 "{m} m en línea recta": "{m} m em linha reta",
 "Reanudar": "Retomar",
 "No": "Não",
 "Sí": "Sim",
 "Al reservar: «{nombre}»": "Ao reservar: «{nombre}»",
 "En Booking: «{nombre}»": "No Booking: «{nombre}»",
 "Apartamento número {n}, {m2} metros: ver sus {fotos} fotos y detalles": "Apartamento número {n}, {m2} metros: ver as {fotos} fotos e os detalhes",
 "Ver fotos y detalles": "Ver fotos e detalhes",
 "Nº {n}": "N.º {n}",
 "Planta abierta": "Espaço aberto",
 "Consultar fechas para el apartamento {n}": "Consultar datas para o apartamento {n}",
 "Dos portales": "Duas entradas",
 "Según el apartamento, la entrada es por {una} o por {otra}. Te lo decimos al confirmar la reserva.": "Consoante o apartamento, a entrada é pela {una} ou pela {otra}. Dizemos-lhe qual ao confirmar a reserva.",
 "Cómo llegar a {calle}": "Como chegar à {calle}",
 "domingo,lunes,martes,miércoles,jueves,viernes,sábado": "domingo,segunda-feira,terça-feira,quarta-feira,quinta-feira,sexta-feira,sábado",
 "enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre": "janeiro,fevereiro,março,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro",
 "{dia} {n} de {mes}": "{dia}, {n} de {mes}",
 "Elige la fecha de llegada y la de salida.": "Escolha a data de chegada e a de partida.",
 "La salida tiene que ser posterior a la llegada.": "A partida tem de ser depois da chegada.",
 "Enviar consulta": "Enviar pedido",
 "Se envía directamente a Apartamentos El Sótano; si no se puede, te dejamos el mensaje para que lo mandes tú.": "Segue diretamente para os Apartamentos El Sótano; se não for possível, deixamos-lhe a mensagem pronta para a enviar por si.",
 "Falta tu nombre, para que sepamos quién escribe.": "Falta o seu nome, para sabermos quem escreve.",
 "Falta un email válido, para poder contestarte.": "Falta um email válido, para lhe podermos responder.",
 "{n} niño": "{n} criança",
 "{n} niños": "{n} crianças",
 "{adultos} y {ninos}": "{adultos} e {ninos}",
 "el Nº {n}": "o N.º {n}",
 "un apartamento": "um apartamento",
 "Hola, somos {quienes}{mascota} y queremos {cual} del {desde} al {hasta} ({noches}).": "Olá, somos {quienes}{mascota} e queremos {cual} de {desde} a {hasta} ({noches}).",
 " con mascota": " com animal de estimação",
 "{n} noche": "{n} noite",
 "{n} noches": "{n} noites",
 "¿Lo tienes libre esas fechas?": "Está disponível nessas datas?",
 "Un saludo,": "Cumprimentos,",
 "Consulta de fechas": "Pedido de datas",
 "Mensaje enviado": "Mensagem enviada",
 "Te contestamos en cuanto podamos.": "Respondemos-lhe assim que pudermos.",
 "No se ha podido enviar solo": "Não foi possível enviar automaticamente",
 "Usa uno de los botones de abajo para mandarlo tú.": "Use um dos botões abaixo para a enviar por si.",
 "Mensaje copiado. Pégalo donde quieras.": "Mensagem copiada. Cole-a onde quiser.",
 "No se ha podido copiar: selecciona el texto y cópialo a mano.": "Não foi possível copiar: selecione o texto e copie-o à mão.",
 "Consultas": "Perguntas",
 "¿Prefieres preguntarnos antes de reservar? Rellena esto y te dejamos escrito el mensaje. Lo envías tú, por email o como prefieras, y te contestamos con la disponibilidad y el precio de esas fechas.": "Prefere perguntar-nos antes de reservar? Preencha isto e deixamos-lhe a mensagem escrita. Depois é só enviá-la, por email ou como preferir, e respondemos-lhe com a disponibilidade e o preço para essas datas.",
 "Cocina completa: placa, horno, microondas, nevera, cafetera y tostadora": "Cozinha completa: placa, forno, micro-ondas, frigorífico, máquina de café e torradeira",
 "Aire acondicionado y calefacción": "Ar condicionado e aquecimento",
 "Artículos de aseo y secador": "Produtos de higiene e secador",
 "Dormitorio: 2 camas individuales": "Quarto: 2 camas de solteiro",
 "Salón: 1 sofá cama": "Sala: 1 sofá-cama",
 "2 camas individuales y sofá cama": "2 camas de solteiro e sofá-cama",
 "Comedor con panelado de madera": "Sala de jantar com paredes revestidas a madeira",
 "Suelo de madera": "Chão de madeira",
 "Entrada por C/ Virgen de la Soledad, 6": "Entrada pela C/ Virgen de la Soledad, 6",
 "Planta abierta: 1 cama de matrimonio": "Espaço aberto: 1 cama de casal",
 "Cama de matrimonio, en planta abierta": "Cama de casal, em espaço aberto",
 "Celosía de listones": "Divisória de ripas",
 "Entrada propia": "Entrada própria",
 "La barra del antiguo restaurante": "O balcão do antigo restaurante",
 "Dormitorio 1: 2 camas individuales y 1 cama doble": "Quarto 1: 2 camas de solteiro e 1 cama de casal",
 "Dormitorio 2: 3 camas individuales": "Quarto 2: 3 camas de solteiro",
 "Dos dormitorios: cama doble y 5 individuales": "Dois quartos: cama de casal e 5 de solteiro",
 "Dos dormitorios": "Dois quartos",
 "Balcón y terraza": "Varanda e terraço",
 "Mesa ovalada con lámpara de araña": "Mesa oval com lustre",
 "Entrada por C/ Montesinos, 3": "Entrada pela C/ Montesinos, 3",
 "Dormitorio: 1 cama individual y 1 cama doble": "Quarto: 1 cama de solteiro e 1 cama de casal",
 "Cama doble, cama individual y sofá cama": "Cama de casal, cama de solteiro e sofá-cama",
 "Terraza-patio": "Terraço-pátio",
 "Suelo de barro": "Chão de barro",
 "Comedor del Nº 1: mesa gris con sillas de madera y la pared panelada de madera": "Sala de jantar do N.º 1: mesa cinzenta com cadeiras de madeira e a parede revestida a madeira",
 "Dormitorio del Nº 1 con dos camas individuales": "Quarto do N.º 1 com duas camas de solteiro",
 "Salón del Nº 1 con sofá gris, mesa de centro y lámpara de araña": "Sala do N.º 1 com sofá cinzento, mesa de centro e lustre",
 "Cocina del Nº 1 con horno, placa y armarios blancos": "Cozinha do N.º 1 com forno, placa e armários brancos",
 "Zona de estar del Nº 1 con sofá gris": "Zona de estar do N.º 1 com sofá cinzento",
 "Cocina y comedor del Nº 1 con suelo de madera": "Cozinha e sala de jantar do N.º 1 com chão de madeira",
 "Baño del Nº 1 con ducha de cristal": "Casa de banho do N.º 1 com duche de vidro",
 "Entrada con puertas de madera y el pasillo de salida": "Entrada com portas de madeira e o corredor de saída",
 "Salón del Nº 4: el mueble largo de madera con cajones, sofá azul y mesa redonda": "Sala do N.º 4: o móvel comprido de madeira com gavetas, sofá azul e mesa redonda",
 "Salón del Nº 4 con mecedora, sofá azul y el mueble de madera": "Sala do N.º 4 com cadeira de baloiço, sofá azul e o móvel de madeira",
 "Comedor y salón del Nº 4 con mesa blanca y sofá azul": "Sala de jantar e sala de estar do N.º 4 com mesa branca e sofá azul",
 "Salón-comedor del Nº 4 con mesa blanca, sofá azul y mecedora": "Sala comum do N.º 4 com mesa branca, sofá azul e cadeira de baloiço",
 "Salón del Nº 4 con sofá azul y un cuadro de la Venus de Botticelli": "Sala do N.º 4 com sofá azul e um quadro da Vénus de Botticelli",
 "Puerta antigua de madera con vidriera verde y ámbar": "Porta antiga de madeira com vitral verde e âmbar",
 "Dormitorio del Nº 4 con cama doble, cama individual y mesa con lámpara": "Quarto do N.º 4 com cama de casal, cama de solteiro e mesa com candeeiro",
 "Dormitorio del Nº 4 visto desde la ventana: cama doble con cabecero de forja, cama individual y platos en la pared": "Quarto do N.º 4 visto da janela: cama de casal com cabeceira de ferro forjado, cama de solteiro e pratos na parede",
 "Pasillo del Nº 4 con platos en la pared, el cuadro de la Venus al fondo y el dormitorio a la derecha": "Corredor do N.º 4 com pratos na parede, o quadro da Vénus ao fundo e o quarto à direita",
 "Cocina del Nº 4 con horno, placa, microondas y nevera": "Cozinha do N.º 4 com forno, placa, micro-ondas e frigorífico",
 "Cocina y comedor del Nº 4": "Cozinha e sala de jantar do N.º 4",
 "Vista general del salón y la cocina del Nº 4, con suelo de barro": "Vista geral da sala e da cozinha do N.º 4, com chão de barro",
 "Baño del Nº 4 con ducha de cristal": "Casa de banho do N.º 4 com duche de vidro",
 "Baño del Nº 4 con lavabo y espejo de madera": "Casa de banho do N.º 4 com lavatório e espelho de madeira",
 "El patio: suelo de barro, enrejado de madera, plantas y mesa": "O pátio: chão de barro, treliça de madeira, plantas e mesa",
 "Planta abierta del Nº 2 con la celosía de listones de madera": "Espaço aberto do N.º 2 com a divisória de ripas de madeira",
 "Cocina y comedor del Nº 2 con mesa ovalada blanca": "Cozinha e sala de jantar do N.º 2 com mesa oval branca",
 "Planta abierta del Nº 2: salón, comedor y cama": "Espaço aberto do N.º 2: sala, zona de refeições e cama",
 "Zona de dormir del Nº 2 con cama, sofá y armario de madera": "Zona de dormir do N.º 2 com cama, sofá e roupeiro de madeira",
 "Cocina con campana negra y comedor del Nº 2": "Cozinha com exaustor preto e sala de jantar do N.º 2",
 "Platos de cerámica colgados en la pared del Nº 2": "Pratos de cerâmica pendurados na parede do N.º 2",
 "Baño del Nº 2 con dos lavabos": "Casa de banho do N.º 2 com dois lavatórios",
 "Baño del Nº 2 con lavabo y aseo aparte": "Casa de banho do N.º 2 com lavatório e sanita à parte",
 "Entrada al baño del Nº 2": "Entrada da casa de banho do N.º 2",
 "Comedor del Nº 3: mesa ovalada con lámpara de araña": "Sala de jantar do N.º 3: mesa oval com lustre",
 "Cocina del Nº 3 con lavadora, horno y nevera": "Cozinha do N.º 3 com máquina de lavar roupa, forno e frigorífico",
 "Salón, comedor y cocina del Nº 3": "Sala, zona de refeições e cozinha do N.º 3",
 "Salón del Nº 3 con sofá gris y mesa de centro blanca": "Sala do N.º 3 com sofá cinzento e mesa de centro branca",
 "Salón y cocina del Nº 3 con sofá gris y lavadora": "Sala e cozinha do N.º 3 com sofá cinzento e máquina de lavar roupa",
 "Dormitorio del Nº 3 con cama de cabecero de madera": "Quarto do N.º 3 com cama de cabeceira de madeira",
 "Terraza pequeña del Nº 3 con suelo de barro, mesa y sillas": "Pequeno terraço do N.º 3 com chão de barro, mesa e cadeiras",
 "Baño del Nº 3 con ducha y espejo de madera": "Casa de banho do N.º 3 com duche e espelho de madeira",
 "Fachada del nº 6: planta baja de almagre, panel blanco con el logo y la placa AT": "Fachada do n.º 6: rés-do-chão cor de almagre, painel branco com o logótipo e a placa AT",
 "El patio con el desayuno puesto, enrejado de madera y un ave del paraíso": "O pátio com a mesa do pequeno-almoço posta, treliça de madeira e uma ave-do-paraíso",
 "Mesa del desayuno en el patio, junto al enrejado con macetas": "Mesa do pequeno-almoço no pátio, junto à treliça com vasos",
 "Desayuno en el patio, abierto al cielo y a los tejados": "Pequeno-almoço no pátio, aberto ao céu e aos telhados",
 "Pasillo con la palabra LOVE en madera sobre un papel pintado de hojas oscuras": "Corredor com a palavra LOVE em madeira sobre papel de parede com folhas escuras"
};
